version: 2

build:
  os: macOS Sequoia
  tools:
    python: "3.11"
  apt_packages:
    - graphviz

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

formats:
  - pdf

sphinx:
  configuration: docs/conf.py
