version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.9"
  apt_packages:
    - graphviz

formats:
  - pdf

sphinx:
  configuration: docs/source/conf.py

python:
   install:
     - requirements: docs/requirements.txt